### ISSUE TITLE
Does GNM support nonlinear parameter boundary?

### ISSUE THREAD

**Issue by xtLiu2017** [hturner/gnm#9]
Hi there,
  I'm wondering whether users are allowed to set upper and lower boundary for nonlinear parameters when fitting a GNM model.
  Thanks,
  Xiaotong

**Comment by hturner** [comment]
No this isn't implemented in gnm.

It may be possible to enforce the constraints in a custom "nonlin" term, but this would be messy. For example, suppose we wanted to estimate the parameter `a` which should fall between lower boundary `L` and upper boundary `U`. We can instead estimate `b` in the expression

L + (U - L)*exp(b)/(1 + exp(b))

Such an expression would need to be substituted anywhere in your nonlinear term where you want to enforce such constraints. Standard errors on the parameter of interest `a` might be computed using the delta method, if necessary.

A one-sided boundary would be easier to implement and in the case of a lower constraint it may be reasonable to use `Const(L) + Exp(1)` directly in the formula rather than write a custom "nonlin" function.

**Comment by xtLiu2017** [comment]
Cool, thanks for your timely reply!
 
Xiaotong
